[package]
name = "hazel-client-gpui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
gpui = "0.2.2"
gpui-component = "0.5.0"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
tracing = "0.1.43"
unicode-segmentation = "1.12.0"
