tcp_addr = "0.0.0.0:9898"
udp_addr = "0.0.0.0:9899"

[[text_channels]]
name = "Text Channel 1"

[[text_channels]]
name = "Text Channel 2"

[[voice_channels]]
name = "Voice Channel 1"
max_participants = 10
